# Official: https://quay.io/repository/centos/centos?tab=tags
ARG VERSION_NUM="9"
FROM quay.io/centos/centos:stream$VERSION_NUM
ARG VERSION_NUM
LABEL Author="Rex Zhou <zrx879582094@gmail.com>"

WORKDIR /data

# Copy all files
COPY ./docker/ /data/docker/

# CentOS 8 stream had NO valid mirrors; modify_vault_source.sh rewrites the
# repo baseurls for .el8 (auto-detected via rpm --eval '%{?dist}').
RUN if [ "$VERSION_NUM" = "8" ]; then \
        bash ./docker/modify_vault_source.sh && \
        yum install -y perl 'dnf-command(config-manager)' && \
        yum config-manager --set-enabled powertools; \
    else \
        bash /data/docker/modify_live_source.sh /etc/yum.repos.d/*.repo; \
    fi && \
    yum clean all && yum makecache && \
    yum install -y wget autoconf automake gcc make perl rpm-build pam-devel krb5-devel zlib-devel openssl-devel systemd-devel e2fsprogs-devel && \
    yum install -y epel-release && \
    yum install -y gcc-toolset-13-gcc gcc-toolset-13-gcc-c++ && \
    export PATH=/opt/rh/devtoolset-13/root/bin:$PATH && \    
    yum clean all && \
    echo 'LANG=zh_CN.UTF-8' >> /etc/environment && \
    echo 'LANGUAGE=zh_CN.UTF-8' >> /etc/environment && \
    echo 'LC_ALL=zh_CN.UTF-8' >> /etc/environment && \
    echo 'LC_CTYPE=zh_CN.UTF-8' >> /etc/environment && \
    yum -y install tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone

CMD ["./docker/docker_compile.sh"]
