ARG VERSION_NUM="2023"
FROM amazonlinux:$VERSION_NUM
ARG VERSION_NUM
ARG MIRROR=0
LABEL Author="Rex Zhou <zrx879582094@gmail.com>"

WORKDIR /data

# Copy all files
COPY . /data

RUN export MIRROR="$MIRROR" && \
    bash ./docker/modify_yum_source.sh && \
    if [ "$VERSION_NUM" = "2023" ]; then \
        yum makecache timer && yum install -y libnsl systemd-devel; \
    elif [ "$VERSION_NUM" = "2" ]; then \
        yum makecache fast && yum install -y gtk2-devel systemd-devel; \
    elif [ "$VERSION_NUM" = "1" ]; then \
        yum makecache fast \
    fi && \
    yum groupinstall -y "Development Tools" && \
    yum install -y wget autoconf automake gcc make rpm-build openssl-devel pam-devel krb5-devel zlib-devel libXt-devel libX11-devel perl perl-IPC-Cmd perl-Time-Piece && \
    yum clean all && \
    yum search devtoolset && \
    gcc -v && \
    make -v && \
    echo 'LANG=zh_CN.UTF-8' >> /etc/environment && \
    echo 'LANGUAGE=zh_CN.UTF-8' >> /etc/environment && \
    echo 'LC_ALL=zh_CN.UTF-8' >> /etc/environment && \
    echo 'LC_CTYPE=zh_CN.UTF-8' >> /etc/environment && \
    yum -y install tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone

CMD ["./docker/docker_compile.sh"]
